# .github/release-notes-config.yml

tag_name: '{version}'
body: |
  ## Release {version}

  **Release Date:** {release_date}

  ### Breaking Changes ğŸ› 
  {breaking_changes}

  ### New Features ğŸ‰
  {new_features}

  ### Fixes ğŸ›
  {fixes}

  ### Improvements ğŸ”„
  {improvements}

  ### Other Changes ğŸ“œ
  {other_changes}

  ### Contributors ğŸ™
  {contributors}